"""Add cached briefing to personas

Revision ID: 11e3a9d4c4f2
Revises: 224ef1d0c9e8
Create Date: 2026-03-13 12:54:15.531439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11e3a9d4c4f2"
down_revision: Union[str, Sequence[str], None] = "224ef1d0c9e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("personas", sa.Column("cached_briefing", sa.Text(), nullable=True))
    op.add_column(
        "personas",
        sa.Column("briefing_generated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personas", "briefing_generated_at")
    op.drop_column("personas", "cached_briefing")
    # ### end Alembic commands ###
